
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package comp_proy;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int MASMAS = 44;
  public static final int PARCER = 20;
  public static final int DOSPUNTOS = 26;
  public static final int MENOSMENOS = 45;
  public static final int POR = 31;
  public static final int IDENTIF = 51;
  public static final int DIFERENTE = 39;
  public static final int SYSREAD = 17;
  public static final int CASE = 3;
  public static final int TIPO_STRING = 16;
  public static final int PARABR = 19;
  public static final int PARCURSCER = 22;
  public static final int MENORIGUAL = 43;
  public static final int NOT = 37;
  public static final int AND = 35;
  public static final int ESIGUAL = 38;
  public static final int IGUAL = 28;
  public static final int OR = 36;
  public static final int DIV = 32;
  public static final int MAIN = 7;
  public static final int IF = 6;
  public static final int PARCURSABR = 21;
  public static final int MAYORIGUAL = 42;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int COMPLEMENTO = 34;
  public static final int SYSPRINT = 18;
  public static final int error = 1;
  public static final int COMA = 27;
  public static final int LIT_STRING = 50;
  public static final int TIPO_CHAR = 13;
  public static final int MENOS = 30;
  public static final int MENOR = 41;
  public static final int NULL = 8;
  public static final int LIT_CHAR = 49;
  public static final int LIT_BOOLEANO = 48;
  public static final int BREAK = 2;
  public static final int TIPO_INT = 15;
  public static final int SWITCH = 10;
  public static final int MAYOR = 40;
  public static final int POTENCIA = 33;
  public static final int LIT_FLOTANTE = 47;
  public static final int ELSE = 5;
  public static final int PARCUADCER = 24;
  public static final int WHILE = 11;
  public static final int DEFAULT = 4;
  public static final int TIPO_FLOAT = 14;
  public static final int TIPO_BOOL = 12;
  public static final int LIT_ENTERO = 46;
  public static final int HASHTAG = 25;
  public static final int PARCUADABR = 23;
  public static final int MAS = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BREAK",
  "CASE",
  "DEFAULT",
  "ELSE",
  "IF",
  "MAIN",
  "NULL",
  "RETURN",
  "SWITCH",
  "WHILE",
  "TIPO_BOOL",
  "TIPO_CHAR",
  "TIPO_FLOAT",
  "TIPO_INT",
  "TIPO_STRING",
  "SYSREAD",
  "SYSPRINT",
  "PARABR",
  "PARCER",
  "PARCURSABR",
  "PARCURSCER",
  "PARCUADABR",
  "PARCUADCER",
  "HASHTAG",
  "DOSPUNTOS",
  "COMA",
  "IGUAL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "POTENCIA",
  "COMPLEMENTO",
  "AND",
  "OR",
  "NOT",
  "ESIGUAL",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "MASMAS",
  "MENOSMENOS",
  "LIT_ENTERO",
  "LIT_FLOTANTE",
  "LIT_BOOLEANO",
  "LIT_CHAR",
  "LIT_STRING",
  "IDENTIF"
  };
}

